title: My First Real Website!
author: Keylin Sanchez
email: kbsanchez@usf.edu
description: > # this means to ignore newlines until "baseurl:"
  Learning how to create websites using GitHub Pages!

# social links
github_username:  kbsanchez # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
